apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::925810273594:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-ddmixezO4PzS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::925810273594:user/kalyan
      username: kalyan
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: d9d639e3-5aca-44d4-bada-ae08d3cb90f4
