apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::925810273594:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-U6zS25YkHEXh
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::925810273594:user/kalyan
      username: kalyan
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::925810273594:user/pavan
      username: pavan
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: cccae123-8cf6-4ac6-a134-985041662c20